import type { ChatActiveMessageListProps } from './ChatActiveMessageList'
import type { ChatActiveWorkspaceViewProps } from './chatActiveWorkspaceLayerPropTypes'

export function buildChatActiveMessageListProps({
  conversation: activeConversation,
  provider,
  activityLabel,
  multimodalPolicy,
  memoryStatus,
  regenerableAssistantId,
  messageListBottomPadding,
  visualTopInset,
  viewportHeight,
  goProviders,
  goMemoryReview,
  openAgentWorkflowSettings,
  onApplyStarter,
  refreshSkills,
  removeMessage,
  dialog,
  listRef,
  setComposerPanel,
  motion,
  modeEmptyTitle,
  modeEmptyDescription,
  isStreaming,
  activeActionMessageId,
  activeActions: {
    confirmActionFromMessage,
    repairAgentEvidenceFromMessage,
  },
  layoutState: {
    closeOptionsFromBackground,
    conversationHeaderTopPadding,
    emptyConversationTopPadding,
    messageListLayout,
    messageListTopInset,
  },
  messageListController,
  messageSelectionController,
  conversationTasks,
  setActiveActionMessageId,
}: ChatActiveWorkspaceViewProps): ChatActiveMessageListProps {
  return {
    conversation: activeConversation,
    provider,
    multimodalPolicy,
    memoryStatus,
    modeEmptyTitle,
    modeEmptyDescription,
    activityLabel,
    isStreaming,
    motion,
    conversationTasks,
    regenerableAssistantId,
    viewportHeight,
    messageListBottomPadding,
    messageListLayout,
    emptyConversationTopPadding,
    conversationHeaderTopPadding,
    messageListTopInset,
    visualTopInset,
    listRef,
    dialog,
    onApplyStarter,
    refreshSkills,
    removeMessage,
    openAgentWorkflowSettings,
    goProviders,
    goMemoryReview,
    setComposerPanel,
    closeOptionsFromBackground,
    activeActionMessageId,
    setActiveActionMessageId,
    messageSelectionController,
    messageListController,
    repairAgentEvidenceFromMessage,
    confirmActionFromMessage,
  }
}
