import type { ChatActiveChromeLayerProps } from './ChatActiveChromeLayer'
import type { ChatActiveWorkspaceViewProps } from './chatActiveWorkspaceLayerPropTypes'

export function buildChatActiveChromeLayerProps({
  colors,
  conversation: activeConversation,
  provider,
  providerHealth,
  showOptions,
  chromeCollapsed,
  isStreaming,
  metrics,
  switchableProviders,
  visualTopInset,
  insets,
  mobileViewport,
  compactViewport,
  viewportHeight,
  keyboardLift,
  showBack,
  shellNavigation,
  topChromeInset,
  goHistory,
  goSettings,
  onNewConversation,
  setShowOptions,
  setComposerPanel,
  motion,
  markChromeActive,
  restoreChrome,
  modelAccessSettings,
  settingsTransitionActive,
  updateConversation,
  activeActions: {
    confirmSwitchModel,
  },
  messageSelectionController: {
    copyConversationLink,
  },
  layoutState: {
    collapseChrome,
    showFloatingControlOrb,
  },
  setChromeHeight,
}: ChatActiveWorkspaceViewProps): ChatActiveChromeLayerProps {
  return {
    showFloatingControlOrb,
    colors,
    visualTopInset,
    insets,
    chromeCollapsed,
    isStreaming,
    showOptions,
    mobileViewport,
    compactViewport,
    viewportHeight,
    keyboardLift,
    conversation: activeConversation,
    provider,
    providerHealth,
    metrics,
    showBack,
    shellNavigation,
    topChromeInset,
    restoreChrome,
    collapseChrome,
    markChromeActive,
    goHistory,
    goSettings,
    onNewConversation,
    setShowOptions,
    setComposerPanel,
    switchableProviders,
    onLayoutHeight: setChromeHeight,
    motion,
    modelAccessSettings,
    settingsTransitionActive,
    onCopyLink: () => void copyConversationLink(),
    onDraftChange: (updates) => updateConversation(activeConversation.id, updates),
    onSwitchModel: confirmSwitchModel,
  }
}
