export const PROVIDER_PLATFORM_DEFAULT_TEMPERATURE = 0.3
export const PROVIDER_PLATFORM_MIN_TEMPERATURE = 0
export const PROVIDER_PLATFORM_MAX_TEMPERATURE = 2
export const PROVIDER_PLATFORM_ANTHROPIC_MAX_TEMPERATURE = 1
export const PROVIDER_PLATFORM_XIAOMI_MIMO_MAX_TEMPERATURE = 1.5
export const PROVIDER_PLATFORM_MIN_TOP_P = 0
export const PROVIDER_PLATFORM_DEFAULT_TOP_P = 1
export const PROVIDER_PLATFORM_MAX_TOP_P = 1
export const PROVIDER_PLATFORM_MIN_TOP_K = 1
export const PROVIDER_PLATFORM_MAX_TOP_K = 1000
export const PROVIDER_PLATFORM_MIN_OUTPUT_TOKENS = 1
export const PROVIDER_PLATFORM_MIN_CONFIGURED_OUTPUT_TOKENS = 128
export const PROVIDER_PLATFORM_MAX_OUTPUT_TOKENS = 131072

export function clampProviderPlatformTemperature(value: number): number {
  return Math.max(PROVIDER_PLATFORM_MIN_TEMPERATURE, Math.min(PROVIDER_PLATFORM_MAX_TEMPERATURE, value))
}

export function clampProviderPlatformOutputTokens(value: number): number {
  return Math.floor(Math.max(PROVIDER_PLATFORM_MIN_CONFIGURED_OUTPUT_TOKENS, Math.min(PROVIDER_PLATFORM_MAX_OUTPUT_TOKENS, value)))
}
