import { createProviderConversationGenerationPolicy } from '@/modules/providers'
import { resolveProviderRequestParameters } from '@/bootstrap/providerRequestPolicies'
import { getModelConfig } from '@/types/modelCatalog'

const providerConversationGenerationPolicy = createProviderConversationGenerationPolicy({
  getModelConfig,
  resolveProviderRequestParameters,
})

export const resolveConversationGenerationParameterRanges = providerConversationGenerationPolicy.resolveConversationGenerationParameterRanges
export const resolveConversationGenerationParameterDefault = providerConversationGenerationPolicy.resolveConversationGenerationParameterDefault
export const clampConversationGenerationParameter = providerConversationGenerationPolicy.clampConversationGenerationParameter
export const conversationGenerationParameterDiffersFromDefault = providerConversationGenerationPolicy.conversationGenerationParameterDiffersFromDefault
export const resolveConversationGenerationParameterRequest = providerConversationGenerationPolicy.resolveConversationGenerationParameterRequest
export const clampToParameterRange = providerConversationGenerationPolicy.clampToParameterRange
